version: "3.3"
services:
  app:
    container_name: weighttracker
    restart: always
    build: .
    ports:
      - "5000:5000"
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"